services:
  loki:
    image: grafana/loki:latest
    environment:
      TZ: ${SYSTEM_TIMEZONE:-Europe/Moscow}
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - loki

  promtail:
    image: grafana/promtail:latest
    volumes:
      - /var/log:/var/log
    command: -config.file=/etc/promtail/config.yml
    ports:
      - "9080:9080"
    networks:
      - loki
    depends_on:
      - loki
  
  grafana:
    image: grafana/grafana-enterprise:latest
    container_name: grafana-1
    restart: unless-stopped
    ports:
      - '3000:3000'
    networks:
      - loki


networks:
  loki: